/*****************************************************************************
  OME-TIFF definitions 
  Copyright (c) 2009, Center for Bio-Image Informatics, UCSB
 
  Author: Dima V. Fedorov <mailto:dima@dimin.net> <http://www.dimin.net/>
    
  History:
    2009-07-09 12:01 - First creation

  Ver : 1
*****************************************************************************/

#ifndef DIM_OMETIFF_FORMAT_H
#define DIM_OMETIFF_FORMAT_H

#include <vector>
#include <string>

#include <xstring.h>

#include <dim_img_format_interface.h>

//----------------------------------------------------------------------------
// OME-TIFF Structure 
//----------------------------------------------------------------------------
class DOMETiffInfo {
public:
  DOMETiffInfo(): pages(0), channels(0), dim_order("XYCZT") {}

  int pages;    // the value of consequtive images generated by driver
  int channels;
  xstring dim_order;
  double pixel_resolution[4];

  std::vector<std::string> sample_names;
  std::vector<int> display_lut; // rgb -> chan numbers
};


#endif // DIM_OMETIFF_FORMAT_H
